import { Inter } from 'next/font/google'
import './globals.css'
import Prvider from '@/redux/Prvider'
import { Box } from './components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Prvider >
          {children}
        </Prvider>
      </body>
    </html>
  )
}
